app:
  name: api-gateway
  url: 'http://127.0.0.1:3000'
  host: 0.0.0.0
  port: 3001
auth:
  expiresIn: 2592000
  refreshExpiresIn: 3888000
  publicKey: cer/ecdsa-nist-p521-public.pem
  privateKey: cer/ecdsa-nist-p521-private.pem
  ignore: null
encryption:
  securityKeyPrefix: boilerplate
  initializationVector: 2a$10$BEl3fmTztYwlYCBCGe
  encryptionKey: QMW4g15fWmrENLZekjbZW
openRPC:
  enable: true
  path: /rpc/v1
redis:
  host: redis_alpine
  port: 6379
  password: sangvo
